### ISSUE TITLE
Sw4lite : building issue

### ISSUE THREAD

**Issue by Zitagcc** [simgrid/SMPI-proxy-apps#9]
Hi,
It's seems that it doesn't like using smpicxx instead of mpic++.
Check the following link for more details : [https://ci.inria.fr/simgrid/job/SMPI-proxy-apps/lastCompletedBuild/testReport/(root)/TestSuite/ECP_sw4lite/](url)

**Comment by adegomme** [comment]
The issue is with fortran, actually .. you are compiling both fortran 77
(.f files) and fortran 90 (.f90) with smpif90 ... FC should be set to
smpiff for fortran 77 and F90 to smpif90, but I don't know if this one is
being used. This is a problem with their build system, in this case.

2018-03-22 9:41 GMT+01:00 Zitagcc <notifications@github.com>:

**Comment by adegomme** [comment]
in the makefile https://github.com/geodynamics/sw4lite/blob/master/Makefile

for lines 

$(builddir)/%.o:src/%.f90
	/bin/mkdir -p $(builddir)
	cd $(builddir); $(FC) $(FFLAGS) -c ../$< 

$(builddir)/%.mod:src/%.f90
	/bin/mkdir -p $(builddir)
cd $(builddir); $(FC) $(FFLAGS) -c ../$<

$(FC) should be replaced by $(F90), which should point to smpif90.

**Comment by Zitagcc** [comment]
It doesn't works either. Furthermore, as I've a linux OS, the compilation should takes the following configuration : 
  FC  = mpif90
  CXX = mpic++
  OMPOPT = -fopenmp
  EXTRA_LINK_FLAGS = -lgfortran -lblas -llapack
  openmp = no
  debug = no
which mean that there are no issue with Fortran compiler configuration.

**Comment by adegomme** [comment]
No, they are assuming that mpif90 compilers can also compile fortran 77,
which is not sure and wrong imho. And as it's not the case for smpiff/f90
scripts, it does not work.



2018-03-22 11:56 GMT+01:00 Zitagcc <notifications@github.com>:

**Comment by Zitagcc** [comment]
I tried to consider this distinction by giving smpiff and smpif90 
$(builddir)/%.o:src/%.f
	/bin/mkdir -p $(builddir)
	cd $(builddir); smpiff $(FFLAGS) $(IBMF77FLAG) -c ../$< 

$(builddir)/%.o:src/%.f90
	/bin/mkdir -p $(builddir)
	cd $(builddir); $(FC) $(FFLAGS) -c ../$< 

but the building issue remains the same.

**Comment by adegomme** [comment]
Indeed there is a bug here ... the .o files are created in the source
folder, not in the compilation one.

what you can add for now is a line :

cp src/*.o optimize

and....

``'-.,_,.-'``'-.,_,.='``'-.,_,.-'``'-.,_,.='````'-.,_,.-'``'-.,_,.='``


  _________    ____      __      ____    _    __
 /   ____  \   \   \    /  \    /   /   / |  |  |
 |  |    \./    \   \  /    \  /   /   /  |  |  |
 |  |______      \   \/      \/   /   /   '--'  |
 \______   \      \              /    |______   |
        |  |       \     /\     /            |  |
 /`\____|  |        \   /  \   /             |  |
 \_________/         \_/    \_/              |__|

   __       __  ____    ____  _______    ______    __
  |  |     |  | \   \  /   / |   ____|  /    __|  |  |
  |  |     |  |  \   \/   /  |  |__     |   (__   |  |
  |  |     |  |   \      /   |   __|    \__    |  |  |
  |  `----.|  |    \    /    |  |____    __)   |  |__|
  |_______||__|     \__/     |_______|  (_____/   (__)


``'-.,_,.-'``'-.,_,.='``'-.,_,.-'``'-.,_,.='````'-.,_,.-'``'-.,_,.='``
*** Build directory:  optimize  ***


2018-03-22 12:22 GMT+01:00 Zitagcc <notifications@github.com>:

**Comment by adegomme** [comment]
The second issue should be fixed in the trunk of simgrid (not yet in github), files are created in the right folder (but you will still need both smpiff and smpif90 to compile)

**Comment by Zitagcc** [comment]
Ok, I see. Thank you for help.

**Comment by mquinson** [comment]
I sync'ed the github repo, so the second issue is gone. 

The one that remains, ie, the fact that this project tries to compile Fortran90 and Fortran code, also seem to be a bug in our code. Given that there is no difference between smpiff and smpif90, I don't see the point of the latter. Do we plan to introduce separate scripts to compile Fortran 2003 and Fortran 2005, all of them relying on the same gfortran?

I gave `smpiff` the ability to compile f90 and F90 files too, and I guess that this will fix this bug. Please @adegomme feel free to revert if you strongly disagree.

**Comment by mquinson** [comment]
It seems that simgrid/simgrid@40ff80e56a57386d702617d101c049335f540eac is not enough, as the object files are still missing at link time. 
```
cd optimize; smpicxx -O3 -I../src -I../src/double -o sw4lite main.o EW.o Sarray.o Source.o SuperGrid.o GridPointSource.o time_functions.o EW_cuda.o ew-cfromfort.o rhs4sg.o rhs4sg_rev.o EWCuda.o CheckPoint.o Parallel_IO.o EW-dg.o MaterialData.o MaterialBlock.o Polynomial.o SecondOrderSection.o Filter.o TimeSeries.o sacsubc.o curvilinear-c.o rhs4sgcurv.o rhs4sgcurv_rev.o rhs4th3fort.o boundaryOp.o addsgd.o solerr3.o bcfort.o type_defs.o lglnodes.o dgmodule.o metric.o curvilinear4sg.o freesurfcurvisg.o -lgfortran -lblas -llapack
c++: error: rhs4th3fort.o: No such file or directory
c++: error: boundaryOp.o: No such file or directory
c++: error: addsgd.o: No such file or directory
c++: error: solerr3.o: No such file or directory
c++: error: bcfort.o: No such file or directory
c++: error: metric.o: No such file or directory
c++: error: curvilinear4sg.o: No such file or directory
c++: error: freesurfcurvisg.o: No such file or directory
Makefile:239: recipe for target 'sw4lite' failed
```
https://ci.inria.fr/simgrid/job/SMPI-proxy-apps/lastCompletedBuild/testReport/(root)/TestSuite/ECP_sw4lite/

**Comment by mquinson** [comment]
This is finally fixed by 16510e73dc219170c584512ee62841ef41149116. Thus closing.
